### ISSUE TITLE
Undefined offset: 1 in SCurl

### ISSUE THREAD

**Issue by dimmitri** [easmith/selectel-storage-php-class#22]
Undefined offset: 1 in /vendor/easmith/selectel-storage/src/SCurl.php:193
Stack trace:
#0 /vendor/easmith/selectel-storage/src/SCurl.php(193): yii\base\ErrorHandler->handleError()
#1 /vendor/easmith/selectel-storage/src/SCurl.php(133): easmith\selectel\storage\SCurl->parseHead()
#2 /vendor/easmith/selectel-storage/src/SelectelStorage.php(59): easmith\selectel\storage\SCurl->request()

**Comment by re8us** [comment]
@dimmitri а на каком вы хостинге? У меня с 18 ноября начали виснуть некоторые curl запросы к облаку (один из 10-20 шт). Запрос отправляется, долго ждем ответа (бывало и десятки минут), а в ответе типа HTTP-Code 0, даже не ошибка. Ну или curl сам прерывает ожидание и выдает ерунду, которую не может обработать класс...

По смыслу в ваша ошибка говорит об аналогичной ситуации не класс не смог распарсить заголовки ответа сервера...

прикладываю ошибки, которые ловил у себя (это именно из-за неверного/пустого ответа на curl или оборванного запроса curl, неясно)
<img width="1402" alt="Снимок экрана 2019-11-03 в 20 42 32" src="https://user-images.githubusercontent.com/4831984/68088760-9e31b100-fe7b-11e9-954d-3c3806b69825.png">
<img width="1405" alt="Снимок экрана 2019-11-03 в 20 42 22" src="https://user-images.githubusercontent.com/4831984/68088761-9e31b100-fe7b-11e9-960d-122c8c8be200.png">
<img width="788" alt="Снимок экрана 2019-11-03 в 20 41 11" src="https://user-images.githubusercontent.com/4831984/68088762-9e31b100-fe7b-11e9-95d1-6a059e300542.png">
<img width="276" alt="Снимок экрана 2019-11-03 в 20 40 27" src="https://user-images.githubusercontent.com/4831984/68088763-9eca4780-fe7b-11e9-9ef9-613275657a75.png">

**Comment by dimmitri** [comment]
Ошибки всё-таки разные. У вас была ожидаемая ошибка, выброшено исключение SelectelStorageException. И проблема не в библиотеке, она либо на вашей стороне, либо на стороне selectel-а.
Что касается моего issue, то тут ошибка в библиотеке. Эта ошибка была мной получена единожды. И больше не воспроизводилась. Но ошибку отрепортил, на всякий случай.

**Comment by reaferon** [comment]
Данная ошибка возникает, когда невозможно связаться с серверами Селектела. В моем конкретном случае у контейнера был отключен доступ во внешнюю сеть (забыл про это) и я постоянно получал 
`Undefined offset: 1 in /vendor/easmith/selectel-storage/src/SCurl.php:193`
